# Generated by Django 3.2 on 2021-05-14 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('wages', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('property_tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rent_insurance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('water', models.DecimalField(decimal_places=2, max_digits=6)),
                ('electric', models.DecimalField(decimal_places=2, max_digits=6)),
                ('natural_gas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trash', models.DecimalField(decimal_places=2, max_digits=6)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=6)),
                ('car_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone', models.DecimalField(decimal_places=2, max_digits=6)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('other_needs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clothing', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fast_food', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entertainment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('travel', models.DecimalField(decimal_places=2, max_digits=6)),
                ('decor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('other_wants', models.DecimalField(decimal_places=2, max_digits=6)),
                ('savings_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('investments', models.DecimalField(decimal_places=2, max_digits=6)),
                ('emergency', models.DecimalField(decimal_places=2, max_digits=6)),
                ('credit_card', models.DecimalField(decimal_places=2, max_digits=6)),
                ('other_savings', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
